import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Scene } from '../../database/schemas/scene.schema';
import { Model } from 'mongoose';

@Injectable()
export class SceneService {
  constructor(
    @InjectModel(Scene.name) private readonly sceneModel: Model<Scene>,
  ) {}

  async findById(id: string): Promise<Scene> {
    const scene = await this.sceneModel.findById(id).populate('charactersInScene');
    if (!scene) throw new NotFoundException('Scene not found');
    return scene;
  }

  async updateStatus(sceneId: string, status: string) {
    return this.sceneModel.findByIdAndUpdate(sceneId, { status });
  }

  async updateImage(sceneId: string, imageUrl: string, prompt?: string) {
    return this.sceneModel.findByIdAndUpdate(
      sceneId,
      {
        $set: {
          imageUrl,
          prompt,
          status: 'image-done',
        },
      },
      { new: true },
    );
  }
  async bulkInsertScenes(episodeId: string, scenes: Array<any>) {
    const docs = scenes.map((scene, index) => ({
      episodeId,
      orderIndex: index,
      description: scene.description,
      dialogue: scene.dialogue || '',
      prompt: scene.prompt || '',
      charactersInScene: scene.characters || [],
      isAutoGenerated: true,
      status: 'pending',
      createdAt: new Date(),
    }));

    await this.sceneModel.insertMany(docs);
  }
}
