import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';

export const SCENE_STATUS = {
  PENDING: 'pending',
  IMAGE_GENERATING: 'image-generating',
  IMAGE_DONE: 'image-done',
  VIDEO_GENERATING: 'video-generating',
  DONE: 'done',
  ERROR: 'error',
};
@Schema({ timestamps: true })
export class Scene extends Document {
  @Prop({ type: Types.ObjectId, ref: 'Episode', required: true })
  episodeId: Types.ObjectId;

  @Prop()
  orderIndex?: number;

  @Prop()
  description: string;

  @Prop()
  dialogue?: string;

  @Prop()
  prompt: string;

  @Prop()
  imageUrl?: string;

  @Prop()
  videoUrl?: string;

  @Prop([{ type: Types.ObjectId, ref: 'Character' }])
  charactersInScene?: Types.ObjectId[];

  @Prop({ default: false })
  isAutoGenerated: boolean;

  @Prop()
  notes?: string;

  @Prop({
    type: String,
    enum: Object.values(SCENE_STATUS),
    default: SCENE_STATUS.PENDING,
  })
  status: string;
}

export const SceneSchema = SchemaFactory.createForClass(Scene);
SceneSchema.index({ episodeId: 1, orderIndex: 1 });
SceneSchema.index({ status: 1 });
